/gate/source/addSource source1
/gate/source/source1/gps/particle gamma

/gate/source/source1/gps/energytype Mono
/gate/source/source1/gps/monoenergy 140.0 keV
#/gate/source/source1/setActivity 0.0001 Ci        #0.005Ci 40min
/gate/source/source1/setActivity 3e6 Bq

/gate/source/source1/gps/centre 0. 0. 0. mm
/gate/source/source1/gps/type Volume
/gate/source/source1/gps/shape Cylinder
/gate/source/source1/gps/radius 90. mm
/gate/source/source1/gps/halfz 0.5 mm
/gate/source/source1/gps/angtype iso
/gate/source/source1/gps/mintheta 90 deg
/gate/source/source1/gps/maxtheta 90. deg
/gate/source/source1/gps/minphi 120. deg
/gate/source/source1/gps/maxphi 240. deg

/gate/source/source1/visualize 10000 red 2
/gate/source/list
